"""remove_attendance_and_add_sales_orders

Revision ID: 4dc72b460aa4
Revises: a3ee605ac8f8
Create Date: 2026-06-30 22:56:07.850225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4dc72b460aa4'
down_revision: Union[str, Sequence[str], None] = 'a3ee605ac8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('so_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_so_number'), 'sales_orders', ['so_number'], unique=True)
    op.create_index(op.f('ix_sales_orders_tenant_id'), 'sales_orders', ['tenant_id'], unique=False)
    op.create_table('sales_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sales_order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_attendance_employee_email'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_tenant_id'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('employee_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('check_in', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('check_out', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('tenant_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_attendance_tenant_id'), 'attendance', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attendance_employee_email'), 'attendance', ['employee_email'], unique=False)
    op.drop_table('sales_order_items')
    op.drop_index(op.f('ix_sales_orders_tenant_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_so_number'), table_name='sales_orders')
    op.drop_table('sales_orders')
    # ### end Alembic commands ###
