"""local_auth_changes

Revision ID: 5a63eb093e23
Revises: a2b3c4d5e6f7
Create Date: 2026-06-27 17:19:25.747837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a63eb093e23'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'clerk_org_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.alter_column('users', 'clerk_user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'clerk_user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'password_hash')
    op.alter_column('organizations', 'clerk_org_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
