"""add plans table

Revision ID: 8a665bc63253
Revises: ed399729b0ce
Create Date: 2026-06-25 16:10:48.650696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a665bc63253'
down_revision: Union[str, Sequence[str], None] = 'ed399729b0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('popular', sa.Boolean(), nullable=False),
    sa.Column('cta', sa.String(length=100), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    # ### end Alembic commands ###
