"""add_password_change_required

Revision ID: a3ee605ac8f8
Revises: 1f64c989705b
Create Date: 2026-06-30 20:39:16.216578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ee605ac8f8'
down_revision: Union[str, Sequence[str], None] = '1f64c989705b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_change_required', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_change_required')
    # ### end Alembic commands ###
